config/routes.rb
Rails.application.routes.draw do
  mount MissionControl::Jobs::Engine, at: "/jobs"
  devise_for :users, controllers: { registrations: "users/registrations" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  resources :sessions, only: [:index, :update]
  resources :profiles, only: [:show, :update]

  resources :pair_requests, only: [:index] do
    scope module: 'pair_requests' do
      resources :offers, only: [:index, :new, :create] do
        post "accept", on: :member
      end
    end

    get :search, on: :collection
  end

  namespace :users do
    resources :pair_requests, expect: [:edit, :update] do
      patch :add_call_link, on: :member
    end
    resources :offers, only: [:index]
  end

  resources :activities, only: [:index]
end

app/models/pair_request.rb
class PairRequest < ApplicationRecord
  include ActivityGeneratable

  belongs_to :user
  has_many :offers, dependent: nil # TODO: Reconsider
  has_many :periods, as: :periodable, dependent: :destroy, inverse_of: :periodable
  has_many :sessions, as: :sessionable
  has_many :taggings, as: :taggable
  has_many :tags, through: :taggings

  validates :description, :subject, :duration, presence: true
  validates :duration, numericality: { greater_than: 0 }

  scope :active, -> { joins(:periods).merge(Period.future) }

  accepts_nested_attributes_for :periods, allow_destroy: true
  accepts_nested_attributes_for :taggings, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :sessions, reject_if: :new_record?

  class << self
    def ransackable_associations(auth_object=nil)
      ["tags", "user", "periods"]
    end

    def ransackable_attributes(auth_object=nil)
      ["duration"]
    end
  end

  def has_accepted_offer?
    offers.accepted.exists?
  end
end

app/controllers/pair_requests/offers_controller.rb
class PairRequests::OffersController < ApplicationController
  include Authenticated

  def index
    @pair_request = current_user.pair_requests.find_by(id: params[:pair_request_id])

    authorize @pair_request, policy_class: PairRequests::OfferPolicy

    @offers = @pair_request.offers.joins(:period).includes(:offerer, :period).order("accepted_at, periods.start_at desc")
  end

  def new
    @pair_request = PairRequest.find(params[:pair_request_id])
    @offer = @pair_request.offers.build(offerer: current_user)
  end

  def create
    @pair_request = PairRequest.find(params[:pair_request_id])
    @offer = @pair_request.offers.build(offer_params.merge(offerer: current_user))

    if @offer.save
      respond_to do |format|
        format.html { redirect_to pair_requests_path, notice: "We have sent your offer, good luck!" }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def accept
    offer = Offer.find(params[:id])

    authorize offer, policy_class: PairRequests::OfferPolicy

    Offers::Accept
      .call(offer)
      .either(
        -> (success) { redirect_to pair_request_offers_path, notice: "You just scheduled yourself a new pairing session. Happy pairin!" },
        -> (failure) { render :index, status: :unprocessable_entity }
      )
  end

  private

  def offer_params = params.require(:offer).permit(:message, :period_id)
end

app/controllers/pair_requests_controller.rb
class PairRequestsController < ApplicationController
  include Authenticated
  def index
    @q = PairRequest.ransack(params[:q])
    @pagy, @pair_requests = pagy_countless(
      PairRequest
        .includes(:periods, :tags, :user)
        .active
        .where.not(user_id: current_user.id)
        .all
    )

    render "scrollable_list" if params[:page]
  end

  def search
    @q = PairRequest
      .includes(:tags, :periods, :user)
      .left_joins(:tags, :periods, :user)
      .ransack(params[:q].compact_blank)
    @pagy, @pair_requests = pagy_countless(@q.result(distinct: true))

    render "scrollable_list" if params[:page]
  end
end

app/controllers/users/pair_requests_controller.rb
class Users::PairRequestsController < ApplicationController
  include Authenticated

  def index
    @pair_requests = current_user.pair_requests.includes(:sessions).order(created_at: :desc)
  end

  def new
    @pair_request = current_user.pair_requests.build
  end

  def create
    @pair_request = current_user.pair_requests.build(pair_request_params)

    if @pair_request.save
      respond_to do |format|
        format.html { redirect_to users_pair_requests_path, notice: "Request posted! Good luck" }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def add_call_link
    @pair_request = current_user.pair_requests.find(params[:id])

    authorize @pair_request, policy_class: Users::PairRequestPolicy

    if @pair_request.update(add_call_link_params)
      respond_to do |format|
        format.turbo_stream { flash.now[:notice] = "Successfuly added!" }
      end
    end
  end

  private

  def add_call_link_params
    params.require(:pair_request).permit(sessions_attributes: [:call_link, :id])
  end

  def pair_request_params
    params
      .require(:pair_request)
      .permit(
        :subject,
        :description,
        :duration,
        periods_attributes: [:start_at, :_destroy],
        taggings_attributes: [:tag_id, :_destroy, tag_attributes: [:name]]
      )
  end
end

app/helpers/pair_requests/offers_helper.rb
module PairRequests::OffersHelper
  def hide_accept_btn?(offer)
    offer.pair_request.has_accepted_offer? || offer.expired?
  end

  def display_overlay?(offer)
    offer.pair_request.has_accepted_offer? && !offer.accepted?
  end
end

app/views/pair_requests/_next_page.html.erb
<% if @pagy.next %>
  <%= turbo_frame_tag(
        "pair-requests-page-#{@pagy.next}",
        # autoscroll: true,
        loading: :lazy,
        src: pagy_url_for(@pagy, @pagy.next),
        target: "_top"
      ) do %>
  <% end %>
<% end %>

app/views/pair_requests/_pair_request.html.erb
<div class="mb-12 border-2 pb-4 border-black rounded-t-md bg-white shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
  <div class="border-b-2 border-black py-4 px-2 rounded-t-md bg-green">
    <h3 class="font-bold text-xl"><%= pair_request.subject %></h3>
  </div>
  <div class="md:flex max-h-fit px-2 py-4">
    <div class="w-full md:w-7/12" data-controller="read-more" data-read-more-more-text-value="Read more" data-read-more-less-text-value="Read less">
      <p class="read-more-content" data-read-more-target="content">
        <%= pair_request.description %>
      </p>

      <button data-read-more-target="btn" data-action="read-more#toggle">Read more</button>
    </div>

    <div class="w-full mt-4 md:mt-0 md:w-5/12">
      <% pair_request.periods.each do |period| %>
        <div class="w-full flex md:items-center md:justify-end gap-x-1 mt-1">
          <div class="rounded-xl text-sm border-2 border-black px-2 font-semibold">
            <%= period.start_at.to_fs(:short) %>
          </div>
          <span class="block font-bold">:</span>
          <div class="rounded-xl text-sm border-2 border-black px-2 font-semibold">
            <%= period.end_at.to_fs(:short) %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="flex w-full overflow-x-scroll justify-start space-x-2 py-2 px-2 mb-6">
    <% pair_request.tags.each do |tag| %>
      <div class="max-w-max whitespace-nowrap rounded-full border-2 border-black bg-orange px-2 py-1 text-xs 2xl:text-sm font-bold shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] transition-all hover:translate-x-[3px] hover:translate-y-[3px] hover:shadow-none">
        <%= tag.name %>
      </div>
    <% end %>
  </div>
  <div class="px-4 md:flex md:items-center">
    <div class="md:w-1/2 flex items-center gap-x-2">
      <figure class="border-2 border-black w-12 h-12 overflow-hidden rounded-md">
        <%= image_tag pair_request.user.image_url %>
      </figure>

      <div>
        <p><%= pair_request.user.name %></p>
        <span class="text-sm">
          <%= pair_request.user.profession %>
          <span class="text-xl font-bold">.</span>
          <%= pair_request.user.level&.titleize %>
        </span>
      </div>
    </div>
    <div class="md:w-1/2 mt-4 md:mt-0 md:flex md:justify-end">
      <% if pair_request.offers.pluck(:offerer_id).include?(current_user.id) %>
        <p>You have already sent an offer</p>
      <% else %>
        <%= link_to(
          "Apply",
          new_pair_request_offer_path(pair_request.id),
          class: "flex md:w-1/2 cursor-pointer items-center justify-center rounded-md border-2 border-black bg-purple px-10 py-3 font-bold shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] transition-all hover:translate-x-[3px] hover:translate-y-[3px] hover:shadow-none",
          data: { turbo: false }
        ) %>
      <% end %>
    </div>
  </div>
</div>

app/views/pair_requests/index.html.erb
<div class="flex flex-col items-center">
  <div class="w-full md:w-3/4 xl:w-4/6 2xl:w-1/2">
    <div class="flex w-full items-center mt-12 pb-8 border-b-4 border-black border-dashed text-center">
      <h3 class="text-5xl font-bold">Pair Programming Requests</h3>
    </div>

    <div class="mt-12" data-controller="reveal">
      <button data-testid="search-btn" class="relative group overflow-hidden items-center w-full flex justify-end mb-2" data-action="click->reveal#toggle" type="button">
        <span class="absolute block font-bold top-0 -right-[60px] transition ease-in-out duration-500 group-hover:-translate-x-24">
          Filter
        </span>
        <%= image_tag "preferences.svg", alt: "filter", class: "z-10 bg-yellow-50" %>
      </button>

      <div class="mb-12 hidden" data-reveal-target="item">
        <%= simple_form_for @q, url: search_pair_requests_path, method: :get, html: { class: "md:flex md:flex-wrap md:justify-between md:gap-y-4" } do |f| %>
          <div class="md:w-5/12">
            <%= f.label :tags_name_eq, "Tags" %>
            <%= f.combobox :tags_name_eq, Tag.all.map { |p| [p.name, p.name] } %>
          </div>

          <div class="md:w-5/12">
            <%= f.input :duration_eq,
              label: "Duration",
              required: false,
              input_html: {
                class: "w-full rounded-md border-2 border-black p-[10px] font-bold shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] outline-none transition-all focus:translate-x-[3px] focus:translate-y-[3px] focus:shadow-none"
              }
            %>
          </div>
          <div class="md:w-5/12">
            <%= f.label :user_level_eq, "User level" %>
            <%= f.combobox :user_level_eq, User::LEVELS.map { |p| [p.titleize, p] } %>
          </div>
          <div class="md:w-5/12">
            <%= f.label :user_language_eq, "User language" %>
            <%= f.combobox :user_language_eq, I18nData.languages.map { |p, v| [v, p] } %>
          </div>
          <div class="md:w-5/12">
            <%= f.input :periods_start_at_gteq,
              as: :string,
              label: "Session starting from",
              required: false,
              input_html: {
                data: {
                  controller: "datepicker",
                  class: "w-full rounded-md border-2  p-[10px] font-bold shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] outline-none transition-all focus:translate-x-[3px] focus:translate-y-[3px] focus:shadow-none"
                }
              }
            %>
          </div>
          <div class="md:w-5/12">
            <%= f.input :periods_end_at_lteq,
              as: :string,
              required: false,
              label: "Session starting to",
              input_html: {
                data: {
                  controller: "datepicker",
                  class: "w-full rounded-md border-2  p-[10px] font-bold shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] outline-none transition-all focus:translate-x-[3px] focus:translate-y-[3px] focus:shadow-none"
                }
              }
            %>
          </div>

          <div class="md:w-full flex justify-center">
            <%= f.submit "Go",
              data: { turbo_frame: "pair-requests" },
              class: "mt-6 flex cursor-pointer items-center rounded-md border-2 border-black bg-purple px-10 py-3 font-bold shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] transition-all hover:translate-x-[3px] hover:translate-y-[3px] hover:shadow-none"
            %>
          </div>
        <% end %>
      </div>

      <%= turbo_frame_tag "pair-requests" do %>
        <%= render @pair_requests %>
        <%= render partial: "pair_requests/next_page" %>
      <% end %>
    </div>
  </div>
</div>

app/views/pair_requests/scrollable_list.html.erb
<%= turbo_frame_tag "pair-requests-page-#{@pagy.page}" do %>
  <%= render @pair_requests %>
  <%= render partial: "next_page" %>
<% end %>

app/views/pair_requests/search.html.erb
<div class="flex justify-center">
  <%# Add filter form here %>

  <%= turbo_frame_tag "pair-requests" do %>
    <%= render @pair_requests %>
    <%= render partial: "next_page" %>
  <% end %>
</div>