config/routes.rb
Rails.application.routes.draw do
  mount MissionControl::Jobs::Engine, at: "/jobs"
  devise_for :users, controllers: { registrations: "users/registrations" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  resources :sessions, only: [:index, :update]
  resources :profiles, only: [:show, :update]

  resources :pair_requests, only: [:index] do
    scope module: 'pair_requests' do
      resources :offers, only: [:index, :new, :create] do
        post "accept", on: :member
      end
    end

    get :search, on: :collection
  end

  namespace :users do
    resources :pair_requests, expect: [:edit, :update] do
      patch :add_call_link, on: :member
    end
    resources :offers, only: [:index]
  end

  resources :activities, only: [:index]
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div
    class="animate-appearThenFade flex items-center justify-center border-2 border-black bg-purple p-5 px-8 font-bold shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]"
    data-controller="removals"
    data-action="animationend->removals#remove"
  >
    <%= message %>
  </div>
<% end %>

app/views/layouts/_landing_nav.html.erb
<div data-controller="home" class="w-full border-b-4 px-2 border-black bg-yellow-50 font-bold sticky top-0 z-10">
  <div class="flex flex-col max-w-screen-xl py-2 mx-auto md:items-center md:justify-between md:flex-row md:px-6 lg:px-8">
    <div class="flex items-center justify-between lg:justify-start">
      <div class="flex items-center justify-center space-x-2">
        <%= link_to root, class: "flex flex-col justify-center items-center" do %>
          <%= image_tag "logo.svg", class: "w-fit h-8 md:h-12" %>
          <span class="text-xl font-bold">pairin</span>
        <% end %>
      </div>

      <button data-action="click->home#toggleNav" class="rounded-lg md:hidden focus:outline-none focus:shadow-outline">
        <%= image_tag "hamburger.svg", class: "w-8 h-8 md:h-20" %>
      </button>
    </div>

    <nav data-home-target="nav" class="flex-col flex-grow mt-4 hidden md:flex md:justify-end md:flex-row">
      <ul class="space-y-2 list-none lg:space-y-0 lg:items-center lg:inline-flex">
        <% if user_signed_in? %>
          <li>
            <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "text-sm" %>
          </li>
        <% else %>
          <li>
            <%= link_to "Login", new_user_session_path, class: "px-2 lg:px-6 py-6 text-sm border-b-2 border-transparent leading-[22px] md:px-3 text-black" %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</div>

app/views/layouts/_nav.html.erb
<aside class="hidden md:block h-screen w-2/12 font-sans absolute border-r-4 border-black border-dashed">
  <div class="relative w-full h-[inherit]">
    <div class="h-16 flex justify-center items-center cursor-pointer transition-all hover:translate-x-[3px] hover:translate-y-[3px]">
      <%= image_tag "logo.svg", class: "w-12 h-12" %>
    </div>
    <div class="<%= active_link_class(pair_requests_path) %> border-t-4 border-black  h-16 flex justify-center items-center cursor-pointer transition-all hover:translate-x-[3px] [&:not(.active)]:hover:bg-orange hover:translate-y-[3px]">
      <%= link_to "Search", pair_requests_path %>
    </div>
    <div data-controller="reveal">
      <div
        data-action="click->reveal#toggle"
        class="border-t-4 flex items-center justify-center border-black h-16 cursor-pointer transition-all hover:translate-x-[3px] [&:not(.active)]:hover:bg-orange hover:translate-y-[3px]"
      >
        Pair Requests
      </div>

      <div
        data-reveal-target="item"
        class="<%= (current_page?(new_users_pair_request_path) || current_page?(users_pair_requests_path) ||  current_page?(users_offers_path)) ? '' : 'hidden' %>"
      >
        <div class="<%= active_link_class(new_users_pair_request_path) %> border-t-2 flex items-center justify-center border-black h-16 cursor-pointer transition-all hover:translate-x-[3px] [&:not(.active)]:hover:bg-orange hover:translate-y-[3px]">
          <%= link_to "New", new_users_pair_request_path %>
        </div>
        <div class="<%= active_link_class(users_pair_requests_path) %> border-t-2 flex items-center justify-center border-black h-16 cursor-pointer transition-all hover:translate-x-[3px] [&:not(.active)]:hover:bg-orange hover:translate-y-[3px]">
          <%= link_to "Opened", users_pair_requests_path %>
        </div>
        <div class="<%= active_link_class(users_offers_path) %> border-t-2 flex items-center justify-center border-black h-16 cursor-pointer transition-all hover:translate-x-[3px] [&:not(.active)]:hover:bg-orange hover:translate-y-[3px]">
          <%= link_to "Applied", users_offers_path %>
        </div>
      </div>
    </div>
    <div class="<%= active_link_class(activities_path) %> border-t-4 border-black h-16 flex justify-center items-center cursor-pointer transition-all hover:translate-x-[3px] [&:not(.active)]:hover:bg-orange hover:translate-y-[3px]">
      <%= link_to "Feed", activities_path %>
    </div>
    <div class="<%= active_link_class(sessions_path) %> border-y-4 border-black  h-16 flex justify-center items-center cursor-pointer transition-all hover:translate-x-[3px] [&:not(.active)]:hover:bg-orange hover:translate-y-[3px]">
      <%= link_to "Sessions", sessions_path %>
    </div>
    <div class="absolute bottom-0 left-0 w-full" data-controller="reveal">
      <div data-reveal-target="item" class="hidden">
        <div class="border-t-2 flex items-center justify-center border-black h-16 cursor-pointer transition-all hover:translate-x-[3px] [&:not(.active)]:hover:bg-orange hover:translate-y-[3px]"><%= link_to "Profile", profile_path(current_user.id) %></div>
        <div class="border-t-2 flex items-center justify-center border-black h-16 cursor-pointer transition-all hover:translate-x-[3px] [&:not(.active)]:hover:bg-orange hover:translate-y-[3px]"><%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete } %></div>
      </div>

      <div
        data-action="click->reveal#toggle"
        class="w-full border-t-4 border-black h-16 flex justify-center items-center cursor-pointer"
      >
        Account
      </div>
    </div>
  </div>
</aside>

<div data-controller="home" class="md:hidden w-full">
  <div data-controller="reveal relative">
    <button data-action="click->reveal#toggle" type="button" class="absolute top-2 right-2">
      <%= image_tag "hamburger.svg", class: "w-8 h-8" %>
    </button>

    <div data-reveal-target="item" class="hidden w-full">
      <div class="h-16 flex justify-center items-center cursor-pointer transition-all hover:translate-x-[3px] hover:translate-y-[3px]">
        <%= image_tag "logo.svg", class: "w-12 h-12" %>
      </div>
      <div data-controller="reveal">
        <div
          data-action="click->reveal#toggle"
          class="border-t-4 border-black h-16 flex justify-center items-center cursor-pointer transition-all hover:translate-x-[3px] hover:translate-y-[3px]">
        >
          Pair Requests
        </div>


        <div data-reveal-target="item" class="hidden">
          <div class="border-t-2 border-black h-16 flex justify-center items-center cursor-pointer transition-all hover:translate-x-[3px] hover:translate-y-[3px]">
            <%= link_to "New", new_users_pair_request_path %>
          </div>
          <div class="border-t-2 border-black h-16 flex justify-center items-center cursor-pointer transition-all hover:translate-x-[3px] hover:translate-y-[3px]">
            <%= link_to "Opened", users_pair_requests_path %>
          </div>
          <div class="border-t-2 border-black h-16 flex justify-center items-center cursor-pointer transition-all hover:translate-x-[3px] hover:translate-y-[3px]">
            <%= link_to "Applied", users_offers_path %>
          </div>
        </div>
      </div>
      <div class="border-t-4 border-black h-16 flex justify-center items-center cursor-pointer transition-all hover:translate-x-[3px] hover:translate-y-[3px]">
        <%= link_to "Feed", activities_path %>
      </div>
      <div data-controller="reveal">
        <div
          data-action="click->reveal#toggle"
          class="border-y-4 border-black h-16 flex justify-center items-center cursor-pointer transition-all hover:translate-x-[3px] hover:translate-y-[3px]">
        >
          Account
        </div>

        <div data-reveal-target="item" class="hidden">
          <div class="border-t-2 border-black h-16 flex justify-center items-center cursor-pointer transition-all hover:translate-x-[3px] hover:translate-y-[3px]">
            <%= link_to "Profile", profile_path(current_user.id) %>
          </div>
          <div class="border-y-2 border-black h-16 flex justify-center items-center cursor-pointer transition-all hover:translate-x-[3px] hover:translate-y-[3px]">
            <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete } %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/app.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pairin - Find pair programming partner quick and easy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="Discover the perfect pair programming partner with Pairin.dev. Enhance your coding skills and collaborate in real-time with developers around the world." />
    <meta name="turbo-refresh-method" content="morph">
    <meta name="robots" content="noindex, nofollow">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_path('logo.svg') %>

    <%= combobox_style_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-yellow-50">
    <div class="overflow-y-scroll h-screen md:flex">
      <div class="md:w-2/12">
        <%= render "layouts/nav" %>
      </div>

      <div class="md:w-10/12 px-4">
        <div id="flash" class="flash">
          <%= render "layouts/flash" %>
        </div>

        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pairin - Find pair programming partner or coding buddy quick and easy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="Discover the perfect pair programming partner or coding buddy with Pairin.dev. Enhance your coding skills and collaborate in real-time with developers around the world." />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/devicon.min.css">

    <%= favicon_link_tag asset_path('logo.svg') %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script>
      !function(t,e){var o,n,p,r;e.__SV||(window.posthog=e,e._i=[],e.init=function(i,s,a){function g(t,e){var o=e.split(".");2==o.length&&(t=t[o[0]],e=o[1]),t[e]=function(){t.push([e].concat(Array.prototype.slice.call(arguments,0)))}}(p=t.createElement("script")).type="text/javascript",p.crossOrigin="anonymous",p.async=!0,p.src=s.api_host.replace(".i.posthog.com","-assets.i.posthog.com")+"/static/array.js",(r=t.getElementsByTagName("script")[0]).parentNode.insertBefore(p,r);var u=e;for(void 0!==a?u=e[a]=[]:a="posthog",u.people=u.people||[],u.toString=function(t){var e="posthog";return"posthog"!==a&&(e+="."+a),t||(e+=" (stub)"),e},u.people.toString=function(){return u.toString(1)+".people (stub)"},o="init capture register register_once register_for_session unregister unregister_for_session getFeatureFlag getFeatureFlagPayload isFeatureEnabled reloadFeatureFlags updateEarlyAccessFeatureEnrollment getEarlyAccessFeatures on onFeatureFlags onSessionId getSurveys getActiveMatchingSurveys renderSurvey canRenderSurvey getNextSurveyStep identify setPersonProperties group resetGroups setPersonPropertiesForFlags resetPersonPropertiesForFlags setGroupPropertiesForFlags resetGroupPropertiesForFlags reset get_distinct_id getGroups get_session_id get_session_replay_url alias set_config startSessionRecording stopSessionRecording sessionRecordingStarted captureException loadToolbar get_property getSessionProperty createPersonProfile opt_in_capturing opt_out_capturing has_opted_in_capturing has_opted_out_capturing clear_opt_in_out_capturing debug".split(" "),n=0;n<o.length;n++)g(u,o[n]);e._i.push([i,s,a])},e.__SV=1)}(document,window.posthog||[]);
      posthog.init(
        'phc_Krufoq9BGSDfbd1xIXnNBvupnlhf4Q8MKKh9Qjk20h3', {
          api_host:'https://eu.i.posthog.com',
          person_profiles: 'identified_only' // or 'always' to create profiles for anonymous users as well
        }
      )
    </script>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-yellow-50">
    <div class="flash">
      <%= render "layouts/flash" %>
    </div>

    <%= render "layouts/landing_nav" %>

    <%= yield %>
  </body>
</html>